import { api } from "@/lib/api";
import { session } from "@/lib/auth";
import { JsonTable, Status, Empty, RecordSummary } from "@/components/ui";
import { monitoringAction } from "@/app/actions";
import { MutationForm } from "@/components/mutation-form";
export const dynamic = "force-dynamic";
export default async function Monitoring({ params }: {
    params: Promise<{
        id: string;
    }>;
}) { const { id } = await params; const [d, user] = await Promise.all([api<Record<string, any>>(`/operator/monitoring/${encodeURIComponent(id)}/comparison`), session()]); const state = String(d.monitoring.state), admin = user?.role === "ADMIN"; const actions = state === "ACTIVE" ? ["pause", "retire"] : ["PAUSED", "SUSPENDED"].includes(state) ? ["resume", "retire"] : []; return <><h1>Monitoring portfolia</h1><p className="muted">ID monitoringu: <code>{id}</code> · pouze simulace</p><div className="card"><Status value={state}/><p>Nasazení {d.monitoring.deployment_id} · srovnávací řada {d.monitoring.baseline_id} · pravidla {d.monitoring.policy_id}</p><p>Poslední důvod: {d.monitoring.state_reason}</p><small>Zahájeno {d.monitoring.started_at} · ukončeno {d.monitoring.ended_at ?? "N/A"}</small></div>{state === "SUSPENDED" && <p className="card muted">Obnovení schvaluje server. Pokud nejsou splněné bezpečnostní podmínky nebo shoda účtu, požadavek odmítne.</p>}<h2>Pravidla vyhodnocení</h2>{d.policy ? <section className="card"><RecordSummary value={d.policy.config}/></section> : <Empty />}<h2>Srovnávací výsledky mimo trénovací období</h2>{d.baseline ? <section className="card"><RecordSummary value={d.baseline.oos_metrics}/><details><summary>Úplná srovnávací řada</summary><pre>{JSON.stringify({ returns: d.baseline.oos_returns, equity: d.baseline.oos_equity }, null, 2)}</pre></details></section> : <Empty />}<h2>Výsledky simulovaného portfolia</h2><JsonTable rows={d.paper_points}/><h2>Historie vyhodnocení</h2><JsonTable rows={d.evaluations}/>{admin && actions.map(action => <MutationForm key={action} action={monitoringAction} title={`${action === "pause" ? "Pozastavení" : action === "resume" ? "Obnovení" : "Ukončení"} monitoringu`} submit={`${action === "pause" ? "Pozastavit" : action === "resume" ? "Obnovit" : "Ukončit"} monitoring`} danger={action === "retire"}><input type="hidden" name="id" value={id}/><input type="hidden" name="action" value={action}/><label>Důvod změny<textarea name="reason" required minLength={3}/></label></MutationForm>)}</>; }
