"use server";
import {revalidatePath} from "next/cache";
import {assertSameOrigin,backendToken,requireSession} from "../lib/auth";
const base=process.env.QUANTLAB_API_URL??"http://127.0.0.1:8000";
async function mutate(path:string,body:Record<string,string>){await assertSameOrigin();const current=await requireSession();const r=await fetch(`${base}${path}`,{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${backendToken(current.role)}`},body:JSON.stringify(body),cache:"no-store"});if(!r.ok)throw new Error(`Akce selhala (${r.status})`);revalidatePath("/");revalidatePath("/risk");revalidatePath("/paper")}
export async function eligibilityAction(form:FormData){const id=String(form.get("id"));const reason=String(form.get("reason"));if(!/^[\w-]{1,64}$/.test(id)||reason.length<3)throw new Error("Evaluace vyžaduje experiment a auditní důvod");await mutate(`/operator/research/experiments/${id}/eligibility`,{reason});revalidatePath(`/research/${id}`)}
export async function promotionAction(form:FormData){const id=String(form.get("id"));const reason=String(form.get("reason"));if(!/^[\w-]{1,64}$/.test(id)||reason.length<3)throw new Error("Promotion vyžaduje experiment a auditní důvod");await mutate(`/operator/research/experiments/${id}/promote`,{reason});revalidatePath(`/research/${id}`)}
export async function riskAction(form:FormData){const action=String(form.get("action"));const confirmation=String(form.get("confirmation"));const reason=String(form.get("reason"));if(!["halt","resume"].includes(action))throw new Error("Neplatná akce");await mutate(`/operator/risk/${action}`,{confirmation,reason})}
export async function monitoringAction(form:FormData){const id=String(form.get("id"));const action=String(form.get("action"));const reason=String(form.get("reason"));const confirmation=String(form.get("confirmation"));if(!/^[\w-]{1,64}$/.test(id)||!["pause","resume","retire"].includes(action)||confirmation!==action.toUpperCase()||reason.length<3)throw new Error("Akce vyžaduje přesné potvrzení a důvod");await mutate(`/paper/monitoring/${id}/${action}`,{reason});revalidatePath(`/paper/monitoring/${id}`)}
export async function reconcile(form:FormData){if(form.get("confirmation")!=="RECONCILE")throw new Error("Potvrzení musí být RECONCILE");await mutate("/reconciliation/run",{});revalidatePath("/data")}
export async function autonomousScheduleAction(form:FormData){const id=String(form.get("deployment_id"));const action=String(form.get("action"));const reason=String(form.get("reason"));if(!/^[\w-]{1,64}$/.test(id)||!["enable","disable"].includes(action)||reason.length<3)throw new Error("Autonomous akce vyžaduje deployment a auditní důvod");await mutate(`/operator/deployments/${id}/autonomous/${action}`,{reason});revalidatePath("/strategies")}
